# Generated by Django 4.2.7 on 2023-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_step',
            field=models.CharField(default='None', max_length=400),
        ),
    ]
