# Generated by Django 4.2.7 on 2024-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
