# Generated by Django 4.2.7 on 2024-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_step',
            field=models.CharField(default='None', max_length=2000),
        ),
    ]
